apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: v3fs-set
spec:
  template:
    metadata:
      name: v3fs-deploy
      labels:
        app: v3fs-deploy
    spec:
      containers:
        - image: iguaziodocker/fuse:unstable
          imagePullPolicy: Always
          name: flex-deploy
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
            - mountPath: /etc/config/v3io
              name: cfg
            - mountPath: /etc/v3io/fuse
              name: etc

      volumes:
        - name: flexvolume-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
        - name: etc
          hostPath:
            path: /etc/v3io/fuse
        - name: cfg
          configMap:
            name: v3fs-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: v3fs-config
data:
  v3io.conf: |
    {
      "version": "1.0",
      "root_path": "/tmp/v3io",
      "fuse_path": "/home/iguazio/igz/clients/fuse/bin/v3io_adapters_fuse",
      "debug": true,
      "clusters": [
          {
                "name": "default",
                "data_url": "tcp://172.31.45.253:1234",
                "api_url": "http://172.31.45.253:8001"
          }
      ]
    }
